name: BTS_Flight_Forecast
channels:
  - defaults
dependencies:
  - python >=3.9,<=3.11 # scikit-learn installation fails for 3.12 python.
  - pip
  - pip:
      - -r requirements.txt
variables:
  -QT_DEBUG_PLUGINS: 1
  -QT_QPA_PLATFORM: offscreen