name: BTS_Flight_Forecast
channels:
  - defaults
dependencies:
  - python >=3.9,<=3.11 # scikit-learn installation fails for 3.12 python.
  #- pyqt5-tools
  - pytest
  - pyqt=5
  # - pytest-qt
  - scikit-learn=1.2
  - requests=2.31
  - pandas=2.2
  - pip
  - pip:
      - pylint==2.15
      # - PyQt5==5.15
      - pytest-qt
      # - pyqt5-tools



