name: BTS_Flight_Forecast
channels:
  - defaults
dependencies:
  - python >=3.9,<=3.11 # scikit-learn installation fails for 3.12 python.
  - pip
  - pip:
      - install PyQt5=5.15
      - install pyqt5-tools
      - install pytest pytest-qt
      - install scikit-learn=1.2
      - install pylint=2.15
      - install requests=2.31
      - install pandas-2.2
